//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wzbalance.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerIP {
            get {
                return ((string)(this["ServerIP"]));
            }
            set {
                this["ServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PageSize {
            get {
                return ((int)(this["PageSize"]));
            }
            set {
                this["PageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font CellFont {
            get {
                return ((global::System.Drawing.Font)(this["CellFont"]));
            }
            set {
                this["CellFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt, style=Bold")]
        public global::System.Drawing.Font HeaderFont {
            get {
                return ((global::System.Drawing.Font)(this["HeaderFont"]));
            }
            set {
                this["HeaderFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection ColumnDisplay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnDisplay"]));
            }
            set {
                this["ColumnDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection ColumnWidth {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnWidth"]));
            }
            set {
                this["ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection ColumnIndex {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnIndex"]));
            }
            set {
                this["ColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int NewContractLocY {
            get {
                return ((int)(this["NewContractLocY"]));
            }
            set {
                this["NewContractLocY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public int NewContractLocX {
            get {
                return ((int)(this["NewContractLocX"]));
            }
            set {
                this["NewContractLocX"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>thhtbh</string>
  <string>sellcontract</string>
  <string>sellman</string>
  <string>pinming</string>
  <string>paihao</string>
  <string>guige</string>
  <string>sellnum</string>
  <string>pricewithtax</string>
  <string>jstj</string>
  <string>jhzt</string>
  <string>tsyq</string>
  <string>selldate</string>
  <string>yf</string>
  <string>kucun</string>
  <string>luhao</string>
  <string>planprice</string>
  <string>rkdbh</string>
  <string>buyman</string>
  <string>buycontract</string>
  <string>location</string>
  <string>jindu</string>
  <string>rkgg</string>
  <string>rkl</string>
  <string>buyprice</string>
  <string>rkrq</string>
  <string>ckdbh</string>
  <string>ckl</string>
  <string>cksj</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection InputOrder {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InputOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1</string>
  <string>3</string>
  <string>4</string>
  <string>5</string>
  <string>6</string>
  <string>7</string>
  <string>8</string>
  <string>9</string>
  <string>10</string>
  <string>11</string>
  <string>17</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ContractInput {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ContractInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>14</string>
  <string>15</string>
  <string>16</string>
  <string>17</string>
  <string>19</string>
  <string>20</string>
  <string>21</string>
  <string>22</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CaiGouInput {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CaiGouInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>23</string>\r\n  <string>24</string>\r\n  <string>25</string>\r\n</ArrayOfString" +
            ">")]
        public global::System.Collections.Specialized.StringCollection SellInput {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SellInput"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public int ContactMngLocX {
            get {
                return ((int)(this["ContactMngLocX"]));
            }
            set {
                this["ContactMngLocX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ContactMngLocY {
            get {
                return ((int)(this["ContactMngLocY"]));
            }
            set {
                this["ContactMngLocY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650")]
        public int ContactMngWidth {
            get {
                return ((int)(this["ContactMngWidth"]));
            }
            set {
                this["ContactMngWidth"] = value;
            }
        }
    }
}
